#+TITLE: Error Ssl Synamic Graph

Traceback (most recent call last):
  File "train_supervised.py", line 219, in <module>
    train_val_test_evalulation_node_prediction(
  File "C:\Users\terng\OneDrive\Documents\Working\tgn\evaluation\eval_node_classification.py", line 125, in train_val_test_evalulation_node_prediction
    decoder_loss.backward()
  File "C:\Users\terng\anaconda3\envs\py38\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\terng\anaconda3\envs\py38\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.
